// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

void initApp() => RustLib.instance.api.crateApiPlenumApiInitApp();

Stream<String> startDiscovery({required BigInt timeoutSecs}) => RustLib
    .instance
    .api
    .crateApiPlenumApiStartDiscovery(timeoutSecs: timeoutSecs);

Stream<String> startSend({
  required String filePath,
  required String peerAddress,
  String? optionalPin,
}) => RustLib.instance.api.crateApiPlenumApiStartSend(
  filePath: filePath,
  peerAddress: peerAddress,
  optionalPin: optionalPin,
);

Stream<String> startReceive({
  required String outputDir,
  required int port,
  required bool announce,
}) => RustLib.instance.api.crateApiPlenumApiStartReceive(
  outputDir: outputDir,
  port: port,
  announce: announce,
);

/// Sends a file over the internet via a relay/signaling server, negotiating a
/// WebRTC data channel. Mirrors `start_send`, but for internet (non-LAN) transfers.
///
/// `ice_servers_json` is a JSON-encoded array of `{ urls: string[], username?:
/// string, credential?: string }`, matching `plenum::signaling::IceServer`.
/// Passed as JSON (rather than a plain FFI struct) because `IceServer` is
/// defined in the `plenum` crate, so flutter_rust_bridge would otherwise
/// generate it as an opaque handle Dart cannot construct field-by-field.
Stream<String> startSendRemote({
  required String filePath,
  required String relayServerUrl,
  required String sessionId,
  required String myPeerId,
  required String iceServersJson,
  required BigInt connectTimeoutSecs,
}) => RustLib.instance.api.crateApiPlenumApiStartSendRemote(
  filePath: filePath,
  relayServerUrl: relayServerUrl,
  sessionId: sessionId,
  myPeerId: myPeerId,
  iceServersJson: iceServersJson,
  connectTimeoutSecs: connectTimeoutSecs,
);

/// Receives a file over the internet via a relay/signaling server, negotiating
/// a WebRTC data channel. Mirrors `start_receive`, but for internet (non-LAN) transfers.
///
/// See [`start_send_remote`] for the `ice_servers_json` shape/rationale.
Stream<String> startReceiveRemote({
  required String outputDir,
  required String relayServerUrl,
  required String sessionId,
  required String myPeerId,
  required String iceServersJson,
  required BigInt connectTimeoutSecs,
}) => RustLib.instance.api.crateApiPlenumApiStartReceiveRemote(
  outputDir: outputDir,
  relayServerUrl: relayServerUrl,
  sessionId: sessionId,
  myPeerId: myPeerId,
  iceServersJson: iceServersJson,
  connectTimeoutSecs: connectTimeoutSecs,
);

/// Generates a display-ready room code for internet transfers, without
/// blocking on a relay-server connection (so the receive UI can show it
/// immediately).
String generateRoomCodeSync() =>
    RustLib.instance.api.crateApiPlenumApiGenerateRoomCodeSync();

/// Generates a random per-connection peer id for internet transfers.
String generatePeerIdSync() =>
    RustLib.instance.api.crateApiPlenumApiGeneratePeerIdSync();
