// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

void initApp() => RustLib.instance.api.crateApiPlenumApiInitApp();

Stream<String> startDiscovery({required BigInt timeoutSecs}) => RustLib
    .instance
    .api
    .crateApiPlenumApiStartDiscovery(timeoutSecs: timeoutSecs);

Stream<String> startSend({
  required String filePath,
  required String peerAddress,
  String? optionalPin,
}) => RustLib.instance.api.crateApiPlenumApiStartSend(
  filePath: filePath,
  peerAddress: peerAddress,
  optionalPin: optionalPin,
);

Stream<String> startReceive({
  required String outputDir,
  required int port,
  required bool announce,
}) => RustLib.instance.api.crateApiPlenumApiStartReceive(
  outputDir: outputDir,
  port: port,
  announce: announce,
);
